---
driver:
  name: vagrant

driver_config:
  requre_chef_omnibus: true
  network:
  customize:
    memory: 1024
    cpus: 1

provisioner:
  name: chef_zero
  chef_omnibus_url: http://sl73gsesaapd002.visa.com/chef/install.sh
  roles_path: '../gse/roles'
  environments_path: '../gse/environments'

platforms:
  - name: rhel-6.5
    driver:
      box_url: http://sl73cirepoapp01.visa.com/pub/vblock/gsesa/bento/opscode_rhel-6.5_chef-provisionerless.box

suites:
  - name: default
    run_list:
      - recipe[visa_deps::default]
    attributes:
    provisioner:
      client_rb:
        environment: workstation
